; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-n16r8]
; Force le téléchargement de la Version 3 via la communauté Pioarduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Spécifications N16R8
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

build_flags = 
    -DBOARD_HAS_PSRAM

; Dépendances
lib_deps = 
    madhephaestus/ESP32Encoder @ ^0.11.6
	sparkfun/SparkFun Qwiic OTOS Arduino Library

;; --- CONFIGURATION UPLOAD SANS FIL (OTA) ---
;upload_protocol = espota
;upload_port = 192.168.1.122  ; <--- Mettre ici l'adresse IP affichée au démarrage dans le terminal
;upload_flags = 
;    --auth=azer  ; <--- Mettre ici la valeur textuelle correspondant à "OTA_PASSWORD"